### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by 7SINS7** [DoggyCraftDK/MyDog#10]
I keep getting:
Server thread/INFO [MyDog] Enabling MyDog v0.0.8
Server thread/INFO [MyDog] Vault detected.
Server thread/INFO [MyDog] Vault not found.
Server thread/ERROR Error occurred while enabling MyDog v0.0.8 (Is it up to date?)

Running 1.14
Vault v1.7.2-b107

**Comment by Fido2603** [comment]
Seems like a duplicate of #9
Closing this issue. I will look into it when I get some time to do so <3
