### ISSUE TITLE
Trouble configuring Xp / Damage / Hp of wolves upon level up

### ISSUE THREAD

**Issue by Syguyful** [DoggyCraftDK/MyDog#12]
I have tried multiple times to customize the hp, attack damage, and required experience for each level. For some reason, Whenever I launch the server my changes are reverted back to their default values. I have tried /md reload, and I make all the changes in the config file while the server is closed. For example, if I set the health value at level 2 to 40, when I launch the server the value will be set back to 21 health. Is there any other information I can provide you to help with this issue?

**Comment by Fido2603** [comment]
I'm gonna reopen issue #11, so if you could provide me with version of MyDog, server version, and maybe try to put the plugin on Debug, and then please send the the startup logs (use something like Pastebin or Gist).
