### ISSUE TITLE
Issue with the plugin

### ISSUE THREAD

**Issue by realsnowy** [DoggyCraftDK/MyDog#2]
> [15:23:57] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.CraftOfflinePlayer cannot be cast to org.bukkit.entity.Player
> 	at dk.fido2603.mydog.listeners.WolfMainListener.onChunkUnload(WolfMainListener.java:334) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.Chunk.unloadCallback(Chunk.java:675) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:326) ~[patched_1.14.4.jar:git-Paper-167]
> 	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$5(PlayerChunk.java:320) ~[patched_1.14.4.jar:git-Paper-167]
> 	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_201]
> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_201]
> 	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_201]
> 	at net.minecraft.server.v1_14_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:101) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:331) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:105) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:298) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:634) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:294) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1021) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-167]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> [15:24:03] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.CraftOfflinePlayer cannot be cast to org.bukkit.entity.Player
> 	at dk.fido2603.mydog.listeners.WolfMainListener.onChunkUnload(WolfMainListener.java:334) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.Chunk.unloadCallback(Chunk.java:675) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:326) ~[patched_1.14.4.jar:git-Paper-167]
> 	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$5(PlayerChunk.java:320) ~[patched_1.14.4.jar:git-Paper-167]
> 	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_201]
> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_201]
> 	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_201]
> 	at net.minecraft.server.v1_14_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:101) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:331) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:105) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:298) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:634) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.runTasks(ChunkProviderServer.java:294) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.aX(MinecraftServer.java:1021) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.executeNext(MinecraftServer.java:1005) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.sleepForTick(MinecraftServer.java:989) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:922) ~[patched_1.14.4.jar:git-Paper-167]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> [15:25:10] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: org.bukkit.craftbukkit.v1_14_R1.CraftOfflinePlayer cannot be cast to org.bukkit.entity.Player
> 	at dk.fido2603.mydog.listeners.WolfMainListener.onChunkUnload(WolfMainListener.java:334) ~[?:?]
> 	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor78.execute(Unknown Source) ~[?:?]
> 	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.14.4.jar:git-Paper-167]
> 	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.14.4.jar:git-Paper-167]
> 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.14.4.jar:git-Paper-167]
> 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:545) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.Chunk.unloadCallback(Chunk.java:675) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$null$4(PlayerChunk.java:326) ~[patched_1.14.4.jar:git-Paper-167]
> 	at com.mojang.datafixers.util.Either$Left.ifLeft(Either.java:43) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.lambda$a$5(PlayerChunk.java:320) ~[patched_1.14.4.jar:git-Paper-167]
> 	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source) ~[?:1.8.0_201]
> 	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:1.8.0_201]
> 	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_201]
> 	at net.minecraft.server.v1_14_R1.PlayerChunkMap$CallbackExecutor.run(PlayerChunkMap.java:101) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerChunk.a(PlayerChunk.java:331) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkMapDistance.a(ChunkMapDistance.java:105) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.tickDistanceManager(ChunkProviderServer.java:298) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.access$200(ChunkProviderServer.java:22) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer$a.executeNext(ChunkProviderServer.java:634) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:154) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:373) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.IWorldReader.getChunkAt(IWorldReader.java:80) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.World.getChunkAt(World.java:334) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.Entity.setLocation(Entity.java:1362) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.internalTeleport(PlayerConnection.java:1229) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1191) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1158) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.a(PlayerConnection.java:1149) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PortalTravelAgent.a(PortalTravelAgent.java:44) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.EntityPlayer.a(EntityPlayer.java:933) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.Entity.doPortalTick(Entity.java:2215) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.Entity.entityBaseTick(Entity.java:398) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.EntityLiving.entityBaseTick(EntityLiving.java:240) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.Entity.tick(Entity.java:370) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.EntityLiving.tick(EntityLiving.java:2285) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.EntityHuman.tick(EntityHuman.java:165) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.EntityPlayer.playerTick(EntityPlayer.java:420) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.PlayerConnection.tick(PlayerConnection.java:146) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.NetworkManager.a(NetworkManager.java:260) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.ServerConnection.c(ServerConnection.java:139) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1231) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1074) ~[patched_1.14.4.jar:git-Paper-167]
> 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:918) ~[patched_1.14.4.jar:git-Paper-167]
> 	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
> [15:26:50] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: null
> [15:30:31] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: null
> [15:30:42] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: null
> [15:31:51] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: null
> [15:32:00] [Server thread/ERROR]: Could not pass event ChunkUnloadEvent to MyDog v0.0.5
> java.lang.ClassCastException: null

**Comment by Fido2603** [comment]
@realsnowy Hm, I got this error while testing at some point too here earlier today, I will look into if I can reproduce it again and push a fix when I run into it again!

It would help a lot if you could try reproducing it again on the newest build, and thanks for the issue <3

**Comment by Fido2603** [comment]
I tried pushing a fix for the issue, check if the issue still persists, otherwise just open the issue again.
Thanks!
