### ISSUE TITLE
Dogs teleport with you into the Nether

### ISSUE THREAD

**Issue by yntel** [DoggyCraftDK/MyDog#20]
Hi!

Love the plugin. I do have one issue to report though - when a player travels to the nether, all of their dogs teleport to them, including ones that are sitting. This can be pretty dangerous for those with lots of dogs.

Is this an intended behaviour or is it a bug?

Thanks!

**Comment by Fido2603** [comment]
Hi,

This should be fixed in #19 and can be downloaded on the newest alpha version (version 0.1.1-alpha)! Can you try that one out?

Cheers,
Hero // Fido2603
