### ISSUE TITLE
Lost dog 

### ISSUE THREAD

**Issue by 24phoebec** [DoggyCraftDK/MyDog#21]
When I do the /mydog comehere 1
it says my dog cannot be found. I haven't had this issue, so I'm not sure what is happening.

**Comment by Fido2603** [comment]
The issue happens if your dog has been moved and/or died while in an unloaded chunk.
The plugin loads the chunk where your dog was last seen, and if not found, it will tell you the error message.

Try visiting the dog's last seen coordinates.
