### ISSUE TITLE
Dogs teleport with Players when sitting

### ISSUE THREAD

**Issue by AstralForce** [DoggyCraftDK/MyDog#3]
I tried this on a roleplay server and when people teleport to an event their dogs all teleport with them even though they were sitting down in their homes.... The dogs all ended up dead... This is a problem lmao

**Comment by Fido2603** [comment]
@AstralForce Oh boi, the return of the sitting dogs teleporting. Were this travelling between worlds? If it is travelling between worlds the Dogs in the chunk unloading will teleport no matter what. Do you know why they end up dying?

**Comment by Fido2603** [comment]
For others looking into the bug, it would have to be something about this line https://github.com/DoggyCraftDK/MyDog/blob/master/src/dk/fido2603/mydog/listeners/WolfMainListener.java#L363

**Comment by AstralForce** [comment]
It is going across worlds, and they die because they spawned on a 5x5 platform with 20+ dogs pushing eachother into the void lmao

**Comment by Fido2603** [comment]
That is intended, because I haven't found any other way to check if a dog is sitting when you are switching worlds, because the dogs automatically sit upon world change.
