### ISSUE TITLE
Dog names don't save

### ISSUE THREAD

**Issue by ZDaddy69** [DoggyCraftDK/MyDog#6]
Hey there. I tried changing the dog's health/damage stats as well as the names in the config and every time it resets back to the original. Any ideas?

**Comment by Fido2603** [comment]
The dogs.yml file is not supposed to be changed, and is kept as a database for the dogs. It can be changed, but it isn't recommended, and you should use the options in the game for changing the name (nametag).

The stats are loaded from the level of the dog, and those stats can be set in the config.yml file.
